---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: hello-api
  namespace: demo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:v0.2.*
spec:
  releaseName: hello-api-dev
  chart:
    git: git@github.com:ipedrazas/flux-repo
    path: charts/hello-api
    ref: master
  values:
    image:
      repository: ipedrazas/hello-api
      tag: v0.2.0.1
      pullPolicy: Always
    replicaCount: 1
    service:
      type: ClusterIP
      port: 5000
    env:
      name: SQUID
